name: "Ryan Bonhardt"
description: "I’m the founder at Maker-Based Education where we’re working to help schools bridge the gap between what students should be and are learning. I have a dream that one day every student will have the chance to learn skills (both hard and soft) that will equip them to be powerful in the real world."

url: "http://ryanbonhardt.com"

paginate: 5

markdown: rdiscount
permalink: pretty
pygments: true