# Dependencies
markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Ryan Bonhardt
tagline:          'Past work, talks, and writings'
description:      'If this is your first time here, this site hosts all of my past work, projects, talks and writings on my exploration of psychology, self-education, health, and improving your self in general.'
url:              http://ryanbonhardt.com
baseurl:          /

author:
  name:           'Ryan Bonhardt'
  url:            http://www.ryanbonhardt.com/

paginate:         5

# Custom vars
version:          2.1.0

# github:
#  repo:           https://github.com/poole/hyde